modLoader='javafml'
loaderVersion='[47,)'
license='MIT'

[[mods]]
modId='improved_scroll'
version='1.0.0'
displayName='Improved Scroll'
authors='Mehanic'
description='Improved Resource Scroll'

[[dependencies.improved_scroll]]
    modId='forge'
    mandatory=true
    versionRange='[47,)'
    ordering='NONE'
    side='BOTH'

[[dependencies.improved_scroll]]
    modId='minecolonies'
    mandatory=true
    versionRange='[1.20.1,)'
    ordering='AFTER'
    side='BOTH'
